### ISSUE TITLE
Gradle task for building executable war with embedded jetty

### ISSUE THREAD

**Issue by gonedays** [abhijitsarkar/build-tools#1]
Hi, abhijitsarkar,

I am trying to get a gradle task for building executable war with embedded jetty, and found your post with the url:
https://discuss.gradle.org/t/self-executing-war-with-embedded-jetty-server-not-the-plugin/4953, and yu mentioned there was a working build file, but the file is removed now. May I ask for the file, please?  Many thanks.

**Comment by asarkar** [comment]
> for building executable war with embedded jetty

Using what framework? Spring Boot? Grails? Play? CDI with JAX-RS? Standalone? Perhaps I can help if you be more specific. The project I referred to in the Gradle forum is a pet project that I've implemented using various technologies over the years.

**Comment by gonedays** [comment]
I am doing a standard web-based project, with springMvc, but without Spring Boot. A standalone one.  With gradle war plugin, the generated war package can be deployed under web container such as tomcat. But now I would like to generate a war package with Jetty embeded, it will be a self-executable one, and can be run with the command java -jar a.war, without external tomcat installation. And of course, the war package can also be deploayed in standard web container.

**Comment by asarkar** [comment]
Is there a reason you can't use Spring Boot and not leverage their support for executable war with Jetty?
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-jetty-instead-of-tomcat

If you do it yourself, and I don't know why you'd when Boot already has a solution for you, you'll have to create the servlet container and HTTP connectors yourself. Here's how:
http://www.eclipse.org/jetty/documentation/current/embedding-jetty.html

Lastly, I don't know if you're aware of it, but Spring's slogan in recent times has been "make jar, not war".

**Comment by gonedays** [comment]
Thanks for your quick reply. 
I know there is Spring Boot solution, and I have the Main class to initiate a jetty container instance with servlet container and HTTP conectors.
But I am looking for a gradle build file to generate a executable war based on the Main class menthoed above.  I want a war but not jar just because the war would be deployed under both embeded container and standard container

**Comment by asarkar** [comment]
In addition to being a very ugly jar, I don't know if that's even possible because when you build an executable jar/war, the entry point is different than when you deploy in a standalone container. You're probably better off building separate jars. You can create Gradle custom configuration to imitate maven profiles.

Anyway, I already provided a link to how to build executable archive using Jetty. If you're expecting me to provide you a readymade solution that you can copy-paste, you barking up the wrong tree. It's your assignment, not mine.

**Comment by gonedays** [comment]
Yes, they have different entry point. But when the war with structure like this:
|---WEB-INF
|     |_ _ _ web.xml
|     |_ _ _ classes
|     |_ _ _ lib
|  
|_ _ _ _ Main.class, initiate jetty instance and setWebresource etc.
|
|_ _ _ _ Jetty classes depended by Main.class

It will be possiable to run under both embeded Jetty and pre-installed tomcat.
(Run command java Main or depoy to tomcat webapps)
I have a build file with Maven refered to this solution https://github.com/todylu/example_executable_war_with_jetty 
But I look for a build file with Gradle now.
Appreciate your patience and help.
